# -*- coding: utf-8 -*-
r"""
llama.cpp 模型管理台 - 后端服务
================================
功能：
  - 扫描 scripts/run-*.bat 自动识别模型
  - 一键启动 / 停止 / 切换模型（统一端口 11434）
  - 状态检测：stopped / loading / running
  - 运行日志查看

启动： 双击 G:\llama.cpp\llama-manager.bat
访问：  http://127.0.0.1:17890
依赖：  仅 Python 标准库
"""
import os, re, glob, json, time, socket, subprocess, threading, sys
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# ---------------------------------------------------------------- 配置加载
# 配置优先级：环境变量 > exe/脚本同目录 llama-manager.json > 默认值
# llama-manager.json 示例（可选，跨电脑部署用）：
#   {"llama_dir": "D:\\llama.cpp", "models_dir": "D:\\models", "port_api": 17890}

def _load_cfg():
    cfg = {}
    if getattr(sys, "frozen", False):
        base = os.path.dirname(sys.executable)
    else:
        base = os.path.dirname(os.path.abspath(__file__))
    p = os.path.join(base, "llama-manager.json")
    if os.path.exists(p):
        try:
            with open(p, "r", encoding="utf-8") as f:
                cfg = json.load(f) or {}
        except Exception:
            cfg = {}
    return cfg

CFG = _load_cfg()

_ENV_ALIAS = {"llama_dir": "LLAMA_CPP_DIR", "models_dir": "LLAMA_MODELS_DIR"}

def cfg_get(key, default):
    """环境变量 > 配置文件 > 默认值"""
    env_name = _ENV_ALIAS.get(key, "LLAMA_" + key.upper())
    v = os.environ.get(env_name)
    if v is not None and v != "":
        return v
    v = CFG.get(key)
    if v is not None and v != "":
        return str(v)
    return default

# 目录配置：默认适配 G 盘本机，另一台电脑可用 llama-manager.json 或环境变量覆盖
LLAMA_DIR = cfg_get("llama_dir", r"G:\llama.cpp")
SCRIPTS   = os.path.join(LLAMA_DIR, "scripts")
SERVER_EXE= os.path.join(LLAMA_DIR, "llama-server.exe")
LOG_DIR   = os.path.join(LLAMA_DIR, "manager", "logs")
BASE      = os.path.dirname(os.path.abspath(__file__))   # 仅开发模式使用
PORT_API  = int(cfg_get("port_api", 17890))
PORT_LLM  = int(cfg_get("port_llm", 11434))
LLM_HEALTH_URL = "http://127.0.0.1:%d/v1/models" % PORT_LLM

os.makedirs(LOG_DIR, exist_ok=True)
_lock = threading.RLock()  # 可重入锁：switch 内部会嵌套调用 stop/start

# ---------------------------------------------------------------- 工具函数

def bat_text(path):
    for enc in ("utf-8", "gbk", "latin-1"):
        try:
            with open(path, "r", encoding=enc) as f:
                return f.read()
        except UnicodeDecodeError:
            continue
    return ""

def parse_script(path):
    """从 bat 文件提取模型元信息（供前端展示 + 启动参数）"""
    text = bat_text(path)
    def val(flag):
        m = re.search(r"--%s\s+(\S+)" % flag, text, re.S)
        return m.group(1) if m else None
    model = val("model")
    size = None
    if model and os.path.exists(model):
        size = round(os.path.getsize(model) / 1e9, 1)
    return {
        "script": os.path.basename(path),
        "path":   path,
        "alias":  val("alias") or os.path.splitext(os.path.basename(path))[0].replace("run-", ""),
        "model_file": os.path.basename(model) if model else "",
        "model_path": model or "",
        "size_gb": size,
        "ctx": int(val("ctx-size") or 0),
        "cache_kv": val("cache-type-k") or "f16",
        "mtp": "draft-mtp" in text,
        "gpu_layers": val("n-gpu-layers") or "99",
        "auto": "auto-generated" in text,
    }

def list_models():
    models = []
    for p in sorted(glob.glob(os.path.join(SCRIPTS, "run-*.bat"))):
        try:
            models.append(parse_script(p))
        except Exception:
            continue
    return models

# ---------------------------------------------------------------- 模型自动发现

# 扫描的模型存放目录（可用 llama-manager.json 的 models_dir 或环境变量 LLAMA_MODELS_DIR 覆盖）
_MODELS_BASE = cfg_get("models_dir", r"G:\models")
MODEL_DIRS = [_MODELS_BASE, os.path.join(_MODELS_BASE, "gguf")]

DEFAULT_BAT = r"""@echo off
title llama-server: {alias} (port {port})
cd /d {llama_dir}
echo ==========================================
echo   {model}
echo   API:   http://localhost:{port}/v1
echo   Model: {alias}
echo ==========================================
llama-server.exe ^
  --model {model} ^
  --alias {alias} ^
  --port {port} ^
  --host 127.0.0.1 ^
  --ctx-size 8192 ^
  --flash-attn on ^
  --cache-type-k q4_0 ^
  --cache-type-v q4_0 ^
  --reasoning off ^
  --fit on ^
  --n-gpu-layers 99
echo.
echo Server stopped. Press any key to close.
pause >nul
rem auto-generated by llama-manager
"""

def auto_gen_script(gguf_path):
    """为没有对应启动脚本的 GGUF 自动生成默认 run-*.bat；返回脚本路径或 None"""
    base = os.path.splitext(os.path.basename(gguf_path))[0].lower().replace(" ", "-")
    script = os.path.join(SCRIPTS, "run-%s.bat" % base)
    if os.path.exists(script):
        return None
    content = DEFAULT_BAT.format(alias=base, model=gguf_path,
                                 port=PORT_LLM, llama_dir=LLAMA_DIR)
    try:
        with open(script, "w", encoding="gbk", newline="\r\n") as f:
            f.write(content)
        return script
    except Exception:
        return None

def rewrite_bat_model(bat_path, new_model_path):
    """重写 bat 里的 --model 路径（用于修复移动后的模型）"""
    text = bat_text(bat_path)
    # 用 lambda 按字面替换，避免路径反斜杠被当作转义序列
    new_text = re.sub(r"(--model\s+)\S+",
                      lambda m: m.group(1) + new_model_path, text)
    if new_text == text:
        return False
    try:
        with open(bat_path, "w", encoding="gbk", newline="\r\n") as f:
            f.write(new_text)
        return True
    except Exception:
        return False

def sync_scripts():
    """扫描模型目录：
    1) 修复 bat 中失效的 --model 路径（文件被移动/改名后）
    2) 为新 GGUF 自动生成启动脚本
    返回 (added, repaired)"""
    added, repaired = [], []
    models = list_models()
    known = set()
    for m in models:
        if m["model_path"]:
            known.add(os.path.normcase(os.path.normpath(m["model_path"])))
    # 1) 修复失效路径
    for m in models:
        if not m["model_path"] or os.path.exists(m["model_path"]):
            continue
        fname = os.path.basename(m["model_path"])
        for d in MODEL_DIRS:
            cand = os.path.join(d, fname)
            if os.path.isfile(cand):
                if rewrite_bat_model(m["path"], cand):
                    repaired.append(m["script"])
                break
    # 2) 新增模型
    for d in MODEL_DIRS:
        if not os.path.isdir(d):
            continue
        for g in glob.glob(os.path.join(d, "*.gguf")):
            if os.path.normcase(os.path.normpath(g)) not in known:
                s = auto_gen_script(g)
                if s:
                    added.append(s)
    return added, repaired

def extract_args(bat_path):
    """从 bat 中提取 llama-server.exe 之后的命令行参数（处理 ^ 续行）"""
    text = re.sub(r"\^\s*\r?\n", " ", bat_text(bat_path))
    tokens = text.split()
    try:
        start = tokens.index("llama-server.exe") + 1
    except ValueError:
        start = 0
    args, i = [], start
    while i < len(tokens):
        t = tokens[i]
        if t.startswith("--"):
            args.append(t)
            if i + 1 < len(tokens) and not tokens[i + 1].startswith("--"):
                args.append(tokens[i + 1])
                i += 1
        i += 1
    return args

def build_args(bat_path, opts=None):
    """基于 bat 参数，按前端设置覆盖/增删参数"""
    args = extract_args(bat_path)
    opts = opts or {}
    d, i = {}, 0
    while i < len(args):
        flag = args[i]
        if i + 1 < len(args) and not args[i + 1].startswith("--"):
            d[flag] = args[i + 1]; i += 2
        else:
            d[flag] = True; i += 1
    def set_val(flag, val):
        if val is None or val == "":
            d.pop(flag, None)
        else:
            d[flag] = str(val)
    if "ctx" in opts:        set_val("--ctx-size", opts.get("ctx"))
    if "cache_k" in opts:    set_val("--cache-type-k", opts.get("cache_k"))
    if "cache_v" in opts:    set_val("--cache-type-v", opts.get("cache_v"))
    if "gpu_layers" in opts: set_val("--n-gpu-layers", opts.get("gpu_layers"))
    if "reasoning" in opts:
        set_val("--reasoning", "on" if opts.get("reasoning") else "off")
    if "flash_attn" in opts:
        set_val("--flash-attn", "on" if opts.get("flash_attn") else "off")
    if "parallel" in opts:      set_val("--parallel", opts.get("parallel"))
    if "threads" in opts:       set_val("--threads", opts.get("threads"))
    if "temp" in opts:          set_val("--temp", opts.get("temp"))
    if "top_p" in opts:         set_val("--top-p", opts.get("top_p"))
    if "repeat_penalty" in opts: set_val("--repeat-penalty", opts.get("repeat_penalty"))
    if "seed" in opts:          set_val("--seed", opts.get("seed"))
    mtp = opts.get("mtp")
    if mtp is not None:
        if mtp:
            d["--spec-type"] = "draft-mtp"
            d["--spec-draft-n-max"] = str(opts.get("mtp_n", 2))
        else:
            d.pop("--spec-type", None)
            d.pop("--spec-draft-n-max", None)
    out = []
    for k, v in d.items():
        out.append(k)
        if v is not True:
            out.append(v)
    return out

# 当前运行模型的记录（用于日志/速度定位；外部手动启停时自动回退到 alias 匹配）
CURRENT = {"script": None, "options": None}

# ---------------------------------------------------------------- 进程控制

def llm_pid():
    """返回当前占用 11434 端口的 PID，无则 None"""
    try:
        res = subprocess.run(["netstat", "-ano"], capture_output=True, timeout=10)
        # Windows 中文系统下 netstat 输出为 GBK，需手动解码
        out = res.stdout.decode("gbk", errors="replace")
    except Exception:
        return None
    for line in out.splitlines():
        if ":%d" % PORT_LLM in line and "LISTENING" in line:
            parts = line.split()
            if parts:
                try:
                    return int(parts[-1])
                except ValueError:
                    pass
    return None

def get_speed(script_name):
    """从日志尾部解析最近一条【生成】速度 tok/s（排除预填充 prompt eval）"""
    if not script_name:
        return None
    logf = os.path.join(LOG_DIR, script_name.replace(".bat", ".log"))
    if not os.path.exists(logf):
        return None
    try:
        with open(logf, "rb") as f:
            f.seek(0, os.SEEK_END)
            size = f.tell()
            f.seek(max(0, size - 131072))   # 读尾部 128KB
            tail = f.read().decode("utf-8", errors="ignore")
        # 新版: "...| eval time = 820 ms / 30 tokens (...35.36 tokens per second)"
        # 旧版: "llama_perf_context_print: eval time = ... tokens per second"
        # 必须排除 prompt 行（prompt eval time = 预填充速度，可达数百 tok/s）
        for line in reversed(tail.splitlines()):
            low = line.lower()
            if ("tokens per second" in low and "eval time" in low
                    and "prompt" not in low):
                m = re.search(r"([\d.]+)\s*tokens? per second", line, re.I)
                if m:
                    return round(float(m.group(1)), 1)
        # 兜底（无 eval 行时取最后一条 tps，避免空白）
        ms = re.findall(r"(\d+\.?\d*)\s*tokens? per second", tail, re.I)
        return round(float(ms[-1]), 1) if ms else None
    except Exception:
        return None

def script_by_alias(alias):
    for m in list_models():
        if m["alias"] == alias:
            return m["script"]
    return None

_tok_cache = {"key": None, "result": None}

def get_tokens(script_name):
    """解析当前会话累计消耗 token（prompt 输入 / eval 输出），按文件 mtime+size 缓存"""
    if not script_name:
        return None
    logf = os.path.join(LOG_DIR, script_name.replace(".bat", ".log"))
    if not os.path.exists(logf):
        return None
    try:
        st = os.stat(logf)
        key = (script_name, st.st_size, st.st_mtime)
        if _tok_cache["key"] == key:
            return _tok_cache["result"]
        with open(logf, "r", encoding="utf-8", errors="ignore") as f:
            text = f.read()
        # 只统计最后一次 START 之后的记录（当前会话）
        idx = text.rfind("START ")
        if idx > 0:
            text = text[idx:]
        # 新版日志（b10644+）: "prompt eval time = 157.14 ms / 19 tokens"、"| eval time = ... ms / 30 tokens"
        p = sum(int(x) for x in re.findall(
            r"prompt eval time\s*=\s*[\d.]+\s*ms\s*/\s*(\d+)\s*tokens", text))
        e = sum(int(x) for x in re.findall(
            r"\|\s*eval time\s*=\s*[\d.]+\s*ms\s*/\s*(\d+)\s*tokens", text))
        # 旧版格式兜底: "prompt eval count = N token(s)" / "eval count = N token(s)"
        if not p and not e:
            p = sum(int(x) for x in re.findall(r"prompt eval count\s*=\s*(\d+)", text))
            e = sum(int(x) for x in re.findall(r"llama_perf_context_print:\s+eval count\s*=\s*(\d+)", text))
        res = {"prompt": p, "eval": e, "total": p + e}
        _tok_cache["key"] = key
        _tok_cache["result"] = res
        return res
    except Exception:
        return None

def llm_status():
    """stopped / loading / running(带模型名+实时速度+token消耗)"""
    pid = llm_pid()
    if not pid:
        return {"state": "stopped", "pid": None, "models": [], "speed": None,
                "tokens": None, "script": CURRENT["script"]}
    try:
        with urllib.request.urlopen(LLM_HEALTH_URL, timeout=2) as r:
            data = json.loads(r.read().decode("utf-8"))
            ids = [m.get("id") for m in data.get("data", [])]
            alias = ids[0] if ids else None
            script = CURRENT["script"] or script_by_alias(alias)
            return {"state": "running", "pid": pid, "models": ids,
                    "speed": get_speed(script), "tokens": get_tokens(script),
                    "script": script}
    except Exception:
        return {"state": "loading", "pid": pid, "models": [], "speed": None,
                "tokens": None, "script": CURRENT["script"]}

def wait_port_free(timeout=15):
    t0 = time.time()
    while time.time() - t0 < timeout:
        if llm_pid() is None:
            return True
        time.sleep(0.5)
    return llm_pid() is None

def wait_ready(timeout=180):
    """等待模型加载完成（/v1/models 可访问）"""
    t0 = time.time()
    while time.time() - t0 < timeout:
        if llm_status()["state"] == "running":
            return True
        time.sleep(2)
    return llm_status()["state"] == "running"

def start_model(script_name, options=None, wait=False):
    """启动指定脚本对应的模型（可带参数覆盖）；返回 (ok, msg)"""
    global CURRENT
    with _lock:
        if llm_pid():
            return False, "端口 %d 已被占用，请先停止当前模型" % PORT_LLM
        meta = next((m for m in list_models() if m["script"] == script_name), None)
        if not meta:
            return False, "未找到脚本 %s" % script_name
        args = build_args(meta["path"], options)
        logf = open(os.path.join(LOG_DIR, script_name.replace(".bat", ".log")),
                    "a", encoding="utf-8", errors="ignore")
        logf.write("\n" + "=" * 50 + "\n[%s] START %s (opts: %s)\n" %
                   (time.strftime("%Y-%m-%d %H:%M:%S"), script_name,
                    json.dumps(options or {}, ensure_ascii=False)))
        logf.flush()
        try:
            subprocess.Popen([SERVER_EXE] + args, stdout=logf,
                             stderr=subprocess.STDOUT, cwd=LLAMA_DIR,
                             creationflags=subprocess.CREATE_NO_WINDOW)
        except Exception as e:
            logf.close()
            return False, "启动失败: %s" % e
        CURRENT["script"] = script_name
        CURRENT["options"] = options or {}
    if wait and not wait_ready():
        return False, "启动超时（模型加载过慢），请查看日志"
    time.sleep(0.5)
    return True, "已启动 %s (PID %s)" % (meta["alias"], llm_pid())

def stop_model(wait=True):
    """停止当前模型；返回 (ok, msg)"""
    global CURRENT
    with _lock:
        pid = llm_pid()
        if not pid:
            return False, "当前没有运行中的模型"
        subprocess.run(["taskkill", "/F", "/T", "/PID", str(pid)],
                       capture_output=True, timeout=10)
        if wait:
            wait_port_free()
        CURRENT["script"] = None
        CURRENT["options"] = None
    return True, "已停止 (PID %s)" % pid

def switch_model(script_name, options=None):
    """先停止当前，再启动目标；返回 (ok, msg)"""
    with _lock:
        if llm_pid():
            stop_model(wait=True)
        return start_model(script_name, options, wait=False)

def restart_model(script_name, options=None):
    """重启（停止 + 启动）；返回 (ok, msg)"""
    with _lock:
        if llm_pid():
            stop_model(wait=True)
        return start_model(script_name, options, wait=False)

# ---------------------------------------------------------------- 系统资源监控

_cpu_lock = threading.Lock()
_cpu_prev = None

def cpu_percent():
    """CPU 总使用率 %（GetSystemTimes 两次采样差值）"""
    global _cpu_prev
    try:
        import ctypes
        class FILETIME(ctypes.Structure):
            _fields_ = [("dwLowDateTime", ctypes.c_uint32),
                        ("dwHighDateTime", ctypes.c_uint32)]
        idle, kernel, user = FILETIME(), FILETIME(), FILETIME()
        ctypes.windll.kernel32.GetSystemTimes(
            ctypes.byref(idle), ctypes.byref(kernel), ctypes.byref(user))
        def to64(ft):
            return (ft.dwHighDateTime << 32) | ft.dwLowDateTime
        now = (to64(idle), to64(kernel), to64(user))
        with _cpu_lock:
            prev = _cpu_prev
            _cpu_prev = now
        if prev is None:
            return None
        idle_d = now[0] - prev[0]
        total_d = (now[1] - prev[1]) + (now[2] - prev[2])
        if total_d <= 0:
            return None
        return round(max(0.0, min(100.0, 100.0 * (1.0 - idle_d / total_d))), 1)
    except Exception:
        return None

def mem_info():
    """物理内存 used/total/pct（GB）"""
    try:
        import ctypes
        class MEMORYSTATUSEX(ctypes.Structure):
            _fields_ = [
                ("dwLength", ctypes.c_uint32), ("dwMemoryLoad", ctypes.c_uint32),
                ("ullTotalPhys", ctypes.c_uint64), ("ullAvailPhys", ctypes.c_uint64),
                ("ullTotalPageFile", ctypes.c_uint64), ("ullAvailPageFile", ctypes.c_uint64),
                ("ullTotalVirtual", ctypes.c_uint64), ("ullAvailVirtual", ctypes.c_uint64),
                ("ullAvailExtendedVirtual", ctypes.c_uint64)]
        ms = MEMORYSTATUSEX()
        ms.dwLength = ctypes.sizeof(ms)
        ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(ms))
        total = ms.ullTotalPhys / 1e9
        used = (ms.ullTotalPhys - ms.ullAvailPhys) / 1e9
        return {"used": round(used, 1), "total": round(total, 1),
                "pct": round(used / total * 100, 1)}
    except Exception:
        return None

def gpu_info():
    """NVIDIA 显存 used/total + 利用率（nvidia-smi）"""
    try:
        out = subprocess.run(
            ["nvidia-smi", "--query-gpu=memory.used,memory.total,utilization.gpu",
             "--format=csv,noheader,nounits"],
            capture_output=True, timeout=5).stdout.decode("utf-8", "ignore")
        parts = [x.strip() for x in out.strip().split(",")]
        used, total, util = float(parts[0]), float(parts[1]), float(parts[2])
        return {"vram_used": round(used / 1024, 1), "vram_total": round(total / 1024, 1),
                "pct": round(used / total * 100, 1), "util": round(util)}
    except Exception:
        return None

# ---------------------------------------------------------------- HTTP 服务

def send_json(handler, obj, code=200):
    body = json.dumps(obj, ensure_ascii=False).encode("utf-8")
    handler.send_response(code)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(body)))
    handler.send_header("Cache-Control", "no-store")
    handler.end_headers()
    handler.wfile.write(body)

class Handler(BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass

    def do_GET(self):
        path = self.path.split("?")[0]
        if path == "/" or path == "/index.html":
            self.serve_index()
        elif path == "/api/models":
            added, repaired = sync_scripts()   # 每次访问自动发现/修复
            send_json(self, {"models": list_models(), "added": len(added),
                             "repaired": len(repaired)})
        elif path == "/api/scan":
            added, repaired = sync_scripts()
            send_json(self, {"ok": True, "added": len(added),
                             "repaired": len(repaired),
                             "scripts": [os.path.basename(a) for a in added]})
        elif path == "/api/status":
            send_json(self, llm_status())
        elif path == "/api/sys":
            send_json(self, {
                "cpu": cpu_percent(),
                "mem": mem_info(),
                "gpu": gpu_info(),
            })
        elif path == "/api/log":
            import urllib.parse
            q = urllib.parse.parse_qs(self.path.split("?", 1)[-1])
            name = (q.get("script") or ["run-gemma4-q6.bat"])[0].replace(".bat", ".log")
            logf = os.path.join(LOG_DIR, name)
            tail = ""
            if os.path.exists(logf):
                with open(logf, "r", encoding="utf-8", errors="ignore") as f:
                    tail = "".join(f.readlines()[-80:])
            send_json(self, {"log": tail})
        else:
            send_json(self, {"error": "not found"}, 404)

    def do_POST(self):
        path = self.path.split("?")[0]
        try:
            length = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(length).decode("utf-8")) if length else {}
        except Exception:
            body = {}
        script = body.get("script", "")
        options = body.get("options") or None
        if path == "/api/start":
            ok, msg = start_model(script, options)
        elif path == "/api/stop":
            ok, msg = stop_model()
        elif path == "/api/switch":
            ok, msg = switch_model(script, options)
        elif path == "/api/restart":
            ok, msg = restart_model(script, options)
        else:
            send_json(self, {"error": "not found"}, 404)
            return
        send_json(self, {"ok": ok, "msg": msg})

    def serve_index(self):
        # 候选路径：exe 同目录（可自定义 HTML）→ _MEIPASS 内嵌 → 开发模式 BASE
        candidates = []
        if getattr(sys, "frozen", False):
            candidates.append(os.path.join(os.path.dirname(sys.executable), "index.html"))
            candidates.append(os.path.join(getattr(sys, "_MEIPASS", ""), "index.html"))
        else:
            candidates.append(os.path.join(BASE, "index.html"))
        for html in candidates:
            if html and os.path.exists(html):
                with open(html, "rb") as f:
                    data = f.read()
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
        send_json(self, {"error": "index.html missing"}, 500)

def start_server():
    """启动 HTTP 服务（供 GUI 入口复用）；成功返回 server 对象，失败返回 None"""
    try:
        srv = ThreadingHTTPServer(("127.0.0.1", PORT_API), Handler)
    except OSError as e:
        print("[llama-manager] 端口 %d 被占用，管理台可能已在运行: %s" % (PORT_API, e))
        return None
    # 启动时自动扫描模型目录
    try:
        added, repaired = sync_scripts()
        print("[llama-manager] 模型扫描完成，新增 %d 个 / 修复 %d 个" % (len(added), len(repaired)))
    except Exception:
        pass
    print("[llama-manager] http://127.0.0.1:%d  (按 Ctrl+C 退出)" % PORT_API)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv

def main():
    srv = start_server()
    if not srv:
        return
    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        srv.shutdown()

if __name__ == "__main__":
    main()
